on:
  push:
    branches:
      - master
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: https://github.com/google-github-actions/release-please-action/tree/v3
        with:
          release-type: python
          package-name: release-please-action
